name: abrar
description: "Abrar Shop mobile app"

publish_to: 'none'
version: 1.0.0+4

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  go_router: ^16.2.2
  google_fonts: ^6.3.1
  flutter_riverpod: ^3.0.0
  in_app_update: ^4.2.5
  firebase_core: ^4.1.0
  cloud_firestore: ^6.0.1
  firebase_auth: ^6.0.2
  firebase_storage: ^13.0.1
  iconsax: ^0.0.8
  shimmer: ^3.0.0
  cached_network_image: ^3.4.1
  fluttertoast: ^9.0.0
  intl: ^0.20.2
  flutter_inappwebview: ^6.1.5
  googleapis_auth: ^2.0.0
  firebase_messaging: ^16.0.2
  flutter_local_notifications: ^19.4.2
  http: ^1.5.0
  path_provider: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4

  flutter_lints: ^6.0.0

flutter_launcher_icons:
  android: "ic_launcher"
  image_path: "assets/images/logo.png"
  min_sdk_android: 21


flutter:
  uses-material-design: true
  assets:
    - assets/data/
    - assets/fonts/
    - assets/images/

  fonts:
    - family: Telenor
      fonts:
        - asset: assets/fonts/Telenor-Light.ttf
          weight: 300
        - asset: assets/fonts/Telenor-Medium.ttf
          weight: 500
        - asset: assets/fonts/Telenor-Bold.ttf
          weight: 800




  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
